---
- name: Update System Packages
  hosts: all
  become: yes
  tasks:
    - name: Update Debian/Ubuntu packages
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
      
    - name: Update RedHat/Fedora packages
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
      
    - name: Check if reboot required (Debian/Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_debian
      when: ansible_os_family == "Debian"
      
    - name: Show reboot status
      debug:
        msg: |
          {% if ansible_os_family == "Debian" and reboot_required_debian.stat.exists %}
          ⚠️  系统需要重启以完成更新
          {% else %}
          ✅ 系统更新完成，无需重启
          {% endif %}
