---
- name: Collect System Information
  hosts: all
  gather_facts: yes
  tasks:
    - name: System Overview
      debug:
        msg: |
          === 系统信息 ===
          主机名: {{ inventory_hostname }}
          IP地址: {{ ansible_host }}
          操作系统: {{ ansible_distribution }} {{ ansible_distribution_version }}
          内核版本: {{ ansible_kernel }}
          架构: {{ ansible_architecture }}
          CPU核心: {{ ansible_processor_vcpus }}
          内存: {{ (ansible_memtotal_mb/1024)|round(1) }}GB
          
    - name: Check disk usage
      shell: df -h
      register: disk_usage
      
    - name: Show disk usage
      debug:
        var: disk_usage.stdout_lines
        
    - name: Check running services
      shell: systemctl list-units --type=service --state=running --no-pager | head -10
      register: services
      ignore_errors: yes
      
    - name: Show top services
      debug:
        var: services.stdout_lines
      when: services is succeeded
